const propertiesData = [
    // Maharashtra
    {
        id: 1,
        title: "Sea View Luxury Villa",
        price: 125000000,
        formattedPrice: "₹12.5 Cr",
        type: "Villa",
        location: "Mumbai",
        state: "Maharashtra",
        address: "South Mumbai, MH",
        image: "https://www.theluxurysignature.com/wp-content/uploads/2015/04/oceanview-luxury-villa-phuket.jpg",
        beds: 5,
        baths: 4,
        area: "4500 sqft",
        isFeatured: true
    },
    {
        id: 2,
        title: "Downtown Penthouse",
        price: 85000000,
        formattedPrice: "₹8.5 Cr",
        type: "Penthouse",
        location: "Mumbai",
        state: "Maharashtra",
        address: "Worli, Mumbai",
        image: "https://images.mansionglobal.com/im-36266027?width=1280&size=1.33333333",
        beds: 3,
        baths: 3,
        area: "2800 sqft",
        isFeatured: true
    },
    {
        id: 3,
        title: "Modern Apartment in Pune",
        price: 15000000,
        formattedPrice: "₹1.5 Cr",
        type: "Apartment",
        location: "Pune",
        state: "Maharashtra",
        address: "Koregaon Park, Pune",
        image: "https://www.guptasen.com/wp-content/uploads/2026/01/Lodha-One-Bund-Garden-Pune-Refined-Art-Deco-Exterior.png",
        beds: 2,
        baths: 2,
        area: "1200 sqft",
        isFeatured: false
    },
    {
        id: 31,
        title: "Spacious Bungalow in Nagpur",
        price: 25000000,
        formattedPrice: "₹2.5 Cr",
        type: "House",
        location: "Nagpur",
        state: "Maharashtra",
        address: "Civil Lines, Nagpur",
        image: "https://assets.architecturaldigest.in/photos/61232bfe2d67973c9fad9fa8/master/w_1600%2Cc_limit/The%2520Nagpur%2520bungalow%2520was%2520designed%2520by%2520architect%2520Hiren%2520Patel%2520.jpg",
        beds: 4,
        baths: 3,
        area: "3000 sqft",
        isFeatured: false
    },

    // Delhi NCR
    {
        id: 4,
        title: "Luxury Apartment in GK",
        price: 60000000,
        formattedPrice: "₹6.0 Cr",
        type: "Apartment",
        location: "Delhi",
        state: "Delhi",
        address: "Greater Kailash, New Delhi",
        image: "https://housing-images.n7net.in/4f2250e8/eefe35c6ce6737d61fcdaf48bff28b90/v0/medium/dlf_queens_court-greater_kailash_ii-delhi-dlf.jpg",
        beds: 3,
        baths: 3,
        area: "2200 sqft",
        isFeatured: false
    },
    {
        id: 5,
        title: "Villa in Gurgaon",
        price: 95000000,
        formattedPrice: "₹9.5 Cr",
        type: "Villa",
        location: "Gurgaon",
        state: "Haryana",
        address: "Golf Course Road, Gurgaon",
        image: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/674185455.jpg?k=6f561d4f111e382a78a8f3ad5fff503ea67bf1b17aed797035d369f761fd174e&o=",
        beds: 5,
        baths: 5,
        area: "5000 sqft",
        isFeatured: true
    },
    {
        id: 6,
        title: "Modern Flat in Noida",
        price: 12000000,
        formattedPrice: "₹1.2 Cr",
        type: "Apartment",
        location: "Noida",
        state: "Uttar Pradesh",
        address: "Sector 150, Noida",
        image: "https://is1-3.housingcdn.com/4f2250e8/ae991aa3f5d8562cc8ba7b37af9ae33a/v0/fs/aashi_modern_apartment_2-sector_73_1-noida-aashi_construction_infra.jpeg",
        beds: 3,
        baths: 2,
        area: "1600 sqft",
        isFeatured: false
    },

    // Karnataka
    {
        id: 7,
        title: "Cozy Family Home",
        price: 45000000,
        formattedPrice: "₹4.5 Cr",
        type: "House",
        location: "Bangalore",
        state: "Karnataka",
        address: "Indiranagar, Bangalore",
        image: "https://www.pufikhomes.com/wp-content/uploads/2018/05/family-home-in-colorado-pufikhomes-1.jpg",
        beds: 4,
        baths: 3,
        area: "2500 sqft",
        isFeatured: true
    },
    {
        id: 8,
        title: "Luxury Villa in Whitefield",
        price: 75000000,
        formattedPrice: "₹7.5 Cr",
        type: "Villa",
        location: "Bangalore",
        state: "Karnataka",
        address: "Whitefield, Bangalore",
        image: "https://www.homznspace.com/wp-content/uploads/2023/01/Villa-view-Sobha-Galera-Sobha-Luxury-Villas-Whitefield.jpg",
        beds: 4,
        baths: 4,
        area: "3500 sqft",
        isFeatured: false
    },
    {
        id: 9,
        title: "Heritage Home in Mysore",
        price: 35000000,
        formattedPrice: "₹3.5 Cr",
        type: "House",
        location: "Mysore",
        state: "Karnataka",
        address: "Gokulam, Mysore",
        image: "https://content3.jdmagicbox.com/v2/comp/mysore/q5/0821px821.x821.230518065123.n7q5/catalogue/heritage-house-kajjihundi-mysore-tourist-attraction-0z8bm4twxd.jpg",
        beds: 3,
        baths: 3,
        area: "2800 sqft",
        isFeatured: false
    },

    // Tamil Nadu
    {
        id: 10,
        title: "Sea Facing Apartment",
        price: 55000000,
        formattedPrice: "₹5.5 Cr",
        type: "Apartment",
        location: "Chennai",
        state: "Tamil Nadu",
        address: "Besant Nagar, Chennai",
        image: "https://homebazaar-blog.s3.ap-south-1.amazonaws.com/knowledge/wp-content/uploads/2022/07/24110639/FeatureImageStylish-Sea-Facing-Flats-In-Mumbai.webp",
        beds: 3,
        baths: 3,
        area: "2000 sqft",
        isFeatured: false
    },
    {
        id: 11,
        title: "Independent House in Coimbatore",
        price: 22000000,
        formattedPrice: "₹2.2 Cr",
        type: "House",
        location: "Coimbatore",
        state: "Tamil Nadu",
        address: "RS Puram, Coimbatore",
        image: "https://images.trovit.com/v1/eyJrZXkiOiIyX2Joa19pbmRlcGVuZGVudF9ob3VzZV9pbl9rZWVyYW5hdGhhbV9mb3JfcmVzYWxlX2NvaW1iYXRvcmVfdGhlX3JlZmVyZW5jZV9udW1iZXJfaXNfMTkyMTEwNjBfNjM4MDAwMDc2Nzc3NzYxOTA3Ni5qcGciLCJicmFuZCI6InRyb3ZpdCIsImNvdW50cnkiOiJJTiIsIndpZHRoIjo2NDAsImhlaWdodCI6NDgwfQ==",
        beds: 4,
        baths: 3,
        area: "2400 sqft",
        isFeatured: false
    },
    {
        id: 12,
        title: "Luxury Villa in ECR",
        price: 80000000,
        formattedPrice: "₹8.0 Cr",
        type: "Villa",
        location: "Chennai",
        state: "Tamil Nadu",
        address: "ECR, Chennai",
        image: "https://www.chennaidreamhomes.com/wp-content/uploads/2024/02/villa-elevation-850x570.jpg",
        beds: 5,
        baths: 5,
        area: "4000 sqft",
        isFeatured: true
    },

    // West Bengal
    {
        id: 13,
        title: "Colonial Style House",
        price: 65000000,
        formattedPrice: "₹6.5 Cr",
        type: "House",
        location: "Kolkata",
        state: "West Bengal",
        address: "Alipore, Kolkata",
        image: "https://shabbyfufu.com/wp-content/uploads/2025/02/Colonial-Home-Style_studio-spitzmillerandnorris_2-scaled.jpg",
        beds: 5,
        baths: 4,
        area: "4200 sqft",
        isFeatured: false
    },
    {
        id: 14,
        title: "Modern Apartment in Salt Lake",
        price: 18000000,
        formattedPrice: "₹1.8 Cr",
        type: "Apartment",
        location: "Kolkata",
        state: "West Bengal",
        address: "Salt Lake City, Kolkata",
        image: "https://resource.rentcafe.com/image/upload/x_0,y_0,w_2500,h_1477,c_crop/q_auto,f_auto,c_lfill,w_419,ar_1.1052631578947365,g_auto/s3/2/102601/luma%20apartments%20mr%20(1%20of%2078).jpg",
        beds: 3,
        baths: 2,
        area: "1400 sqft",
        isFeatured: false
    },
    {
        id: 15,
        title: "Riverside Apartment",
        price: 35000000,
        formattedPrice: "₹3.5 Cr",
        type: "Apartment",
        location: "Kolkata",
        state: "West Bengal",
        address: "Howrah, Kolkata",
        image: "https://www.dlf.in/homes/premium/riverside/assets/images/dlfrevised/Overviewcontractor.jpg",
        beds: 3,
        baths: 3,
        area: "1800 sqft",
        isFeatured: false
    },

    // Telangana
    {
        id: 16,
        title: "High-Rise Apartment",
        price: 42000000,
        formattedPrice: "₹4.2 Cr",
        type: "Apartment",
        location: "Hyderabad",
        state: "Telangana",
        address: "Banjara Hills, Hyderabad",
        image: "https://www.flatinkalyan.com/img/blog/222.jpg",
        beds: 3,
        baths: 3,
        area: "2100 sqft",
        isFeatured: false
    },
    {
        id: 17,
        title: "Luxury Villa in Gachibowli",
        price: 90000000,
        formattedPrice: "₹9.0 Cr",
        type: "Villa",
        location: "Hyderabad",
        state: "Telangana",
        address: "Gachibowli, Hyderabad",
        image: "https://teja9.kuikr.com//r1/20171228/ak_1280_546943770-1514437447_700x700.jpeg",
        beds: 5,
        baths: 5,
        area: "4800 sqft",
        isFeatured: true
    },
    {
        id: 18,
        title: "Spacious Flat in Jubilee Hills",
        price: 55000000,
        formattedPrice: "₹5.5 Cr",
        type: "Apartment",
        location: "Hyderabad",
        state: "Telangana",
        address: "Jubilee Hills, Hyderabad",
        image: "https://newprojects.99acres.com/projects/realplus_homes/realplus_fuji_and_paramount/images/hxpgh1x_1694418408_444770674_med.webp",
        beds: 4,
        baths: 4,
        area: "3000 sqft",
        isFeatured: false
    },

    // Gujarat
    {
        id: 19,
        title: "Bungalow in Ahmedabad",
        price: 32000000,
        formattedPrice: "₹3.2 Cr",
        type: "House",
        location: "Ahmedabad",
        state: "Gujarat",
        address: "Satellite, Ahmedabad",
        image: "https://www.siddhivinayakrealty.com/wp-content/uploads/2022/09/Siddhivinayak-Bella-Casa-Elanza-list.jpg",
        beds: 4,
        baths: 3,
        area: "2800 sqft",
        isFeatured: false
    },
    {
        id: 20,
        title: "Penthouse in Surat",
        price: 45000000,
        formattedPrice: "₹4.5 Cr",
        type: "Penthouse",
        location: "Surat",
        state: "Gujarat",
        address: "Vesu, Surat",
        image: "https://assets.architecturaldigest.in/photos/6008484df93542952b665bd6/16:9/w_2560%2Cc_limit/surat-gujarat-penthouse-featured-image-1366x768.jpg",
        beds: 4,
        baths: 4,
        area: "3200 sqft",
        isFeatured: false
    },
    {
        id: 21,
        title: "Duplex in Vadodara",
        price: 18000000,
        formattedPrice: "₹1.8 Cr",
        type: "House",
        location: "Vadodara",
        state: "Gujarat",
        address: "Alkapuri, Vadodara",
        image: "https://www.vihav.com/wp-content/uploads/vihav-spring-soods-gallery-image-5.webp",
        beds: 3,
        baths: 3,
        area: "2000 sqft",
        isFeatured: false
    },

    // Rajasthan
    {
        id: 22,
        title: "Haveli Style Home",
        price: 50000000,
        formattedPrice: "₹5.0 Cr",
        type: "House",
        location: "Jaipur",
        state: "Rajasthan",
        address: "C-Scheme, Jaipur",
        image: "https://assets.architecturaldigest.in/photos/689b0ee4dbd2b236eebacb50/1:1/w_1080,h_1080,c_limit/cover%20image%20template%203%20(4).jpg",
        beds: 6,
        baths: 5,
        area: "5000 sqft",
        isFeatured: true
    },
    {
        id: 23,
        title: "Modern Villa in Udaipur",
        price: 38000000,
        formattedPrice: "₹3.8 Cr",
        type: "Villa",
        location: "Udaipur",
        state: "Rajasthan",
        address: "Fatehpura, Udaipur",
        image: "https://d4b28jbnqso5g.cloudfront.net/1_H7_A6784_HDR_a4c3156666.webp",
        beds: 4,
        baths: 4,
        area: "3500 sqft",
        isFeatured: false
    },
    {
        id: 24,
        title: "Apartment in Jodhpur",
        price: 12000000,
        formattedPrice: "₹1.2 Cr",
        type: "Apartment",
        location: "Jodhpur",
        state: "Rajasthan",
        address: "Sardarpura, Jodhpur",
        image: "https://arihantjodhpur.com/wp-content/uploads/2020/07/arihant-anchal-jodhpur-affordable-property.jpg",
        beds: 2,
        baths: 2,
        area: "1400 sqft",
        isFeatured: false
    },

    // Kerala
    {
        id: 25,
        title: "Waterfront Villa",
        price: 55000000,
        formattedPrice: "₹5.5 Cr",
        type: "Villa",
        location: "Kochi",
        state: "Kerala",
        address: "Marine Drive, Kochi",
        image: "https://all-kerala.com/wp-content/uploads/2024/06/WhatsApp-Image-2024-06-24-at-13.06.50_a141e414.jpg",
        beds: 4,
        baths: 4,
        area: "3000 sqft",
        isFeatured: true
    },
    {
        id: 26,
        title: "Traditional Kerala House",
        price: 28000000,
        formattedPrice: "₹2.8 Cr",
        type: "House",
        location: "Trivandrum",
        state: "Kerala",
        address: "Kowdiar, Trivandrum",
        image: "https://unwyndambiences.com/crm/public/uploads/gallery/THD2qYzZ1nRUZAi6YdX5TBlOdkr1qL.png",
        beds: 4,
        baths: 3,
        area: "2600 sqft",
        isFeatured: false
    },
    {
        id: 27,
        title: "Apartment in Calicut",
        price: 15000000,
        formattedPrice: "₹1.5 Cr",
        type: "Apartment",
        location: "Calicut",
        state: "Kerala",
        address: "Mavoor Road, Calicut",
        image: "https://www.prisunicbuilders.com/wp-content/uploads/2024/05/PRISUNIC_urbanspace.webp",
        beds: 3,
        baths: 2,
        area: "1600 sqft",
        isFeatured: false
    },

    // Uttar Pradesh
    {
        id: 28,
        title: "Apartment in Lucknow",
        price: 18000000,
        formattedPrice: "₹1.8 Cr",
        type: "Apartment",
        location: "Lucknow",
        state: "Uttar Pradesh",
        address: "Gomti Nagar, Lucknow",
        image: "https://paarthinfrablog.files.wordpress.com/2019/09/luxury-flats-in-lucknow.jpg",
        beds: 3,
        baths: 2,
        area: "1700 sqft",
        isFeatured: false
    },
    {
        id: 29,
        title: "Villa in Agra",
        price: 25000000,
        formattedPrice: "₹2.5 Cr",
        type: "Villa",
        location: "Agra",
        state: "Uttar Pradesh",
        address: "Taj Ganj, Agra",
        image: "https://www.saffronstays.com/_next/image?url=https%3A%2F%2Fik.imagekit.io%2F5tgxhsqev%2Fsaffronstays-media%2F1752755501019107952%3Ftr%3Dw-800%2Ch-500%2Cq-90%2Cf-auto&w=828&q=75",
        beds: 4,
        baths: 3,
        area: "2500 sqft",
        isFeatured: false
    },
    {
        id: 30,
        title: "Flat in Kanpur",
        price: 9000000,
        formattedPrice: "₹90 L",
        type: "Apartment",
        location: "Kanpur",
        state: "Uttar Pradesh",
        address: "Civil Lines, Kanpur",
        image: "https://imagecdn.99acres.com/media1/29683/8/593668131M-1767448219705.jpg",
        beds: 2,
        baths: 2,
        area: "1100 sqft",
        isFeatured: false
    },
    {
        id: 30,
        title: "House At Himachal Pradesh",
        price: 90000000,
        formattedPrice: "₹9cr",
        type: "Villa",
        location: "Mandi",
        state: "Himachal Pradesh",
        address: "Civil Lines, Kanpur",
        image: "https://media-cdn.tripadvisor.com/media/photo-s/2d/6b/b7/ec/caption.jpg",
        beds: 2,
        baths: 2,
        area: "1100 sqft",
        isFeatured: false
    }
];

if (typeof module !== 'undefined') {
    module.exports = propertiesData;
}
